In [ ]:
# Exercise: ex09_create_sequence_array
# 9- Crie o array NumPy apresentado, sem escrever explicitamente os seus valores.
# ([[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28],
#  [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29],
#  [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [6]:
import numpy as np

In [7]:
sequence = np.arange(1,31)

In [ ]:
final_array_correct = sequence.reshape(3, 10, order='F') # F-order ensures the array is filled column-by-column, 
                                                         # reflecting the Fortran-style or column-major order.

In [12]:
print(final_array_correct)

[[ 1  4  7 10 13 16 19 22 25 28]
 [ 2  5  8 11 14 17 20 23 26 29]
 [ 3  6  9 12 15 18 21 24 27 30]]
