In [1]:
# Exercise: ex10_bmi_calculation_numpy

'''
10- Suponha que se pretende avaliar o índice de massa corporal (IMC) de um grupo de pessoas, a
partir dos seus registos de altura e peso. Sabendo que o IMC de cada pessoa é dado pelo
quociente entre o seu peso e o quadrado da sua altura, implemente todas as tarefas que se
seguem, usando as funcionalidades do package NumPy.

a) Crie 2 arrays. O primeiro unidimensional, contendo os nomes de um grupo de 10
pessoas, que escolherá arbitrariamente, e o outro bidimensional 2x10, com os pesos e
alturas dessas pessoas, guardados nas respetivas linhas. Para não ter que introduzir,
um a um, todos esses valores, gere-os aleatoriamente respeitando as seguintes
restrições: todos valores inteiros; os pesos deverão situar-se entre 50 e 100 Kg; e as
alturas entre 150 e 200 cm
'''

import numpy as np

In [2]:
np.random.seed(42) # For reproducibility 

In [4]:
NAMES = np.array([
    "João", "Olivia", "Noah", "Ana", "Oliver", 
    "Ava", "Maria", "Rui", "William", "Sofia"
])


In [5]:
weights_kg = np.random.randint(50, 101, 10)
heights_cm = np.random.randint(150, 201, 10).astype(float)
body_data = np.array([weights_kg, heights_cm])

In [17]:
print(f"Weights (kg): {weights_kg}")
print(f"Heights (cm): {heights_cm}")
print(f"Combined Data (2x10):\n{body_data}")

Weights (kg): [88 78 64 92 57 70 88 68 72 60]
Heights (cm): [160. 173. 185. 189. 173. 152. 171. 151. 173. 193.]
Combined Data (2x10):
[[ 88.  78.  64.  92.  57.  70.  88.  68.  72.  60.]
 [160. 173. 185. 189. 173. 152. 171. 151. 173. 193.]]


In [ ]:
# b) Calcule, e guarde num novo array, o índice de massa corporal de cada uma das pessoas.

bmi = body_data[0] / (body_data[1] / 100) ** 2
print(f"BMI Array:\n{bmi.round(2)}")

BMI Array:
[34.37 26.06 18.7  25.76 19.05 30.3  30.09 29.82 24.06 16.11]


array([34.375     , 26.06167931, 18.69978086, 25.75515803, 19.04507334,
       30.29778393, 30.09473   , 29.82325337, 24.05693475, 16.10781497])

In [13]:
# c) Mostre como se classificam os IMC das pessoas de acordo com as seguintes categorias:
# “Baixo” se IMC<18.5; “Elevado” se IMC>25; e “Ideal” se 18.5≤IMC≤25.

is_low = bmi < 18.5
is_high = bmi > 25.0
is_ideal = np.logical_and(bmi >= 18.5, bmi <= 25.0)

print(f"BMI Low (<18.5): {NAMES[is_low]}")
print(f"BMI Ideal (18.5 - 25.0): {NAMES[is_ideal]}")
print(f"BMI High (>25.0): {NAMES[is_high]}")

BMI Low (<18.5): ['Sofia']
BMI Ideal (18.5 - 25.0): ['Noah' 'Oliver' 'William']
BMI High (>25.0): ['João' 'Olivia' 'Ana' 'Ava' 'Maria' 'Rui']


In [ ]:
#d) Mostre todos os atributos das pessoas por ordem crescente do IMC.
sorted_indices = np.argsort(bmi)

names_sorted = NAMES[sorted_indices]
weights_sorted = weights_kg[sorted_indices]
heights_sorted = heights_cm[sorted_indices]
bmi_sorted = bmi[sorted_indices]

sorted_attributes = np.stack([
    names_sorted,
    weights_sorted.astype(str),
    heights_sorted.astype(str),
    bmi_sorted.round(2).astype(str)
], axis=1)

print(f"{'Name':<10} | {'Weight (kg)':<12} | {'Height (cm)':<12} | {'BMI'}")
print("-" * 50)
for row in sorted_attributes:
    print(f"{row[0]:<10} | {row[1]:<12} | {row[2]:<12} | {row[3]}")


--- D) All Attributes Sorted by BMI (Ascending) ---
Name       | Weight (kg)  | Height (cm)  | BMI
--------------------------------------------------
Sofia      | 60           | 193.0        | 16.11
Noah       | 64           | 185.0        | 18.7
Oliver     | 57           | 173.0        | 19.05
William    | 72           | 173.0        | 24.06
Ana        | 92           | 189.0        | 25.76
Olivia     | 78           | 173.0        | 26.06
Rui        | 68           | 151.0        | 29.82
Maria      | 88           | 171.0        | 30.09
Ava        | 70           | 152.0        | 30.3
João       | 88           | 160.0        | 34.37


In [15]:
# e) Mostre o desvio padrão dos pesos e das alturas.

std_dev_weights = np.std(weights_kg)
std_dev_heights = np.std(heights_cm)

print(f"Weight Standard Deviation: {std_dev_weights:.2f} kg")
print(f"Height Standard Deviation: {std_dev_heights:.2f} cm")

Weight Standard Deviation: 11.71 kg
Height Standard Deviation: 13.74 cm


In [16]:
# f) Mostre as pessoas com peso superior à média.

average_weight = np.mean(weights_kg)
is_above_average = weights_kg > average_weight

print(f"Average Weight: {average_weight:.2f} kg")
print(f"People with weight > Average: {NAMES[is_above_average]}")

Average Weight: 73.70 kg
People with weight > Average: ['João' 'Olivia' 'Ana' 'Maria']
